FROM mcr.microsoft.com/playwright:v1.63.0-noble@sha256:eff16c30e6f3f4af0a03fa4b706120d5e9b0891c344a27d64559aff5900a4a27

ARG BUN_VERSION=1.3.14
RUN npm install --global "bun@${BUN_VERSION}"

WORKDIR /work
